Fixing pol bash script

diff --git a/bin/pol b/bin/pol
--- a/bin/pol
+++ b/bin/pol
@@ -16,4 +16,60 @@ EOF
     exit 1
 fi
 
-node dist/pol.js "$@"
+for arg in "$@"; do
+    shift
+    case "$arg" in  
+        '--in')    set -- "$@" '-i' ;;
+        '--out')   set -- "$@" '-o' ;;
+        '--err')   set -- "$@" '-e' ;;
+        '--keep')  set -- "$@" '-k' ;;
+        *)       set -- "$@" "$arg" ;;
+    esac
+done
+
+# default
+IN="out"
+OUT="out/ok"
+ERR="out/err"
+KEEP=0
+
+OPTIND=1
+while getopts "ki:o:e:" opt
+do
+    case "$opt" in
+        'k') KEEP=1 ;;
+        'i') IN=$OPTARG ;;
+        'o') OUT=$OPTARG ;;
+        'e') ERR=$OPTARG ;;
+    esac
+done
+
+shift $(expr $OPTIND - 1) # remove options from positional parameter
+
+for f in ${IN}/*; do
+
+    if [ ! -f $f ]; then
+        continue
+    fi
+
+    BASENAME=$(basename -- $f)
+
+    TMPERROR=$(mktemp)
+
+    echo -n "$f : "
+    node dist/pol.js "$f" > ${TMPERROR} 2>&1
+
+    if [ $? -eq 0 ]; then
+        echo "OK" 
+        cat ${TMPERROR} >&2
+        rm ${TMPERROR}
+    else
+        echo "FAILED"
+        cat ${TMPERROR} >&2
+        mv ${TMPERROR} ${ERR}/${BASENAME}
+    fi
+
+    if [ $KEEP -eq 0 ]; then 
+        rm $f
+    fi
+done
